version: '3'
name: react-nest-keycloak
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Password123!
    volumes:
      - ./realm:/opt/keycloak/data/import
    ports:
      - "8088:8080"
    command: start-dev --import-realm